name: example
description: An example app for SmartButton.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_smart_button:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
